import * as React from 'react';
import { Metadata } from 'next';
import { SectionWrapper } from '@/components/ui/SectionWrapper';
import { Eyebrow } from '@/components/ui/Eyebrow';
import { HexSigil } from '@/components/ui/Logo';
import { Shield, Lock, EyeOff, Database } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Data Integrity Protocols | TEKGUYZ',
  description: 'Our zero-tolerance approach to operational security and data sovereignty.',
};

export default function PrivacyPage() {
  return (
    <div className="relative min-h-screen pt-[60px]">
      {/* Blueprint Background */}
      <div className="bg-blueprint pointer-events-none absolute inset-0 opacity-[0.03] dark:opacity-[0.07]" />
      
      {/* Hero Section */}
      <SectionWrapper layer="authority" className="relative py-24 text-center">
        <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 opacity-[0.03] dark:opacity-[0.05]">
          <HexSigil size={400} className="grayscale" />
        </div>
        
        <Eyebrow layer="authority">Operational Security</Eyebrow>
        <h1 className="mx-auto max-w-[800px] text-[var(--text-5xl)] font-[800] leading-[var(--leading-tight)] tracking-[var(--tracking-tight)] text-[var(--layer-authority-text)]">
          Data Integrity Protocols
        </h1>
        <p className="mx-auto mt-6 max-w-[600px] text-[var(--text-lg)] text-[var(--color-text-secondary)]">
          Privacy is not a policy. It is a technical constraint. We engineer systems where data exposure is mathematically minimized.
        </p>
      </SectionWrapper>

      {/* Content Grid */}
      <SectionWrapper className="pb-32 pt-12">
        <div className="mx-auto max-w-[880px]">
          <div className="grid grid-cols-1 gap-12 md:grid-cols-2">
            {/* Principles */}
            <div className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-bg-secondary)]/50 p-8 backdrop-blur-md">
              <Shield className="mb-4 text-[var(--layer-authority-text)]" size={32} />
              <h2 className="mb-4 text-[var(--text-xl)] font-bold text-[var(--color-text-primary)]">Zero-Knowledge Architecture</h2>
              <p className="text-[var(--text-sm)] leading-[var(--leading-loose)] text-[var(--color-text-secondary)]">
                We implement architectures that ensure we never have to &quot;trust&quot; a third party with your core intellectual property. Data exposure is a failure mode we engineer against from day zero.
              </p>
            </div>

            <div className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-bg-secondary)]/50 p-8 backdrop-blur-md">
              <Lock className="mb-4 text-[var(--layer-authority-text)]" size={32} />
              <h2 className="mb-4 text-[var(--text-xl)] font-bold text-[var(--color-text-primary)]">Data Sovereignty</h2>
              <p className="text-[var(--text-sm)] leading-[var(--leading-loose)] text-[var(--color-text-secondary)]">
                Every byte of data generated by your TEKGUYZ-engineered system is hosted in environments you control. We do not harvest, monetize, or &quot;leverage&quot; client data for secondary markets.
              </p>
            </div>
          </div>

          <div className="mt-16 space-y-12">
            <section className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-bg-secondary)]/30 p-10 backdrop-blur-sm">
              <h3 className="mb-4 text-[var(--text-2xl)] font-bold text-[var(--layer-authority-text)]">1. Information Collection</h3>
              <p className="text-[var(--text-base)] leading-[var(--leading-loose)] text-[var(--color-text-secondary)]">
                We collect only what is operationally necessary. This includes contact information provided during consultation and technical logs required for system maintenance. We do not use tracking pixels or invasive behavioral analytics on our public-facing platforms.
              </p>
            </section>

            <section className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-bg-secondary)]/30 p-10 backdrop-blur-sm">
              <h3 className="mb-4 text-[var(--text-2xl)] font-bold text-[var(--layer-authority-text)]">2. Encryption Standards</h3>
              <p className="text-[var(--text-base)] leading-[var(--leading-loose)] text-[var(--color-text-secondary)]">
                All data in transit is protected by TLS 1.3. Data at rest is encrypted using AES-256. We utilize hardware security modules (HSM) for key management in high-stakes deployments.
              </p>
            </section>

            <section className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-bg-secondary)]/30 p-10 backdrop-blur-sm">
              <h3 className="mb-4 text-[var(--text-2xl)] font-bold text-[var(--layer-authority-text)]">3. Third-Party Integration</h3>
              <p className="text-[var(--text-base)] leading-[var(--leading-loose)] text-[var(--color-text-secondary)]">
                When integrating third-party APIs, we enforce strict data-outbound policies. We audit the privacy frameworks of every vendor before they are allowed into your system&apos;s critical path.
              </p>
            </section>

            <section className="rounded-[var(--radius-md)] border border-[var(--layer-authority-border)] bg-[var(--layer-authority-bg)] p-8">
              <h3 className="mb-2 text-[var(--text-lg)] font-bold text-[var(--layer-authority-text)]">Audit Request</h3>
              <p className="text-[var(--text-sm)] text-[var(--color-text-secondary)]">
                Clients have the right to request a full data audit or system wipe at any time. Contact our engineering team at hello@tekguyz.com to initiate a protocol review.
              </p>
            </section>
          </div>
        </div>
      </SectionWrapper>
    </div>
  );
}
